### ISSUE TITLE
Building System Adaptation

### ISSUE THREAD

**Issue by C-atmaca** [CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers#1]
Old building system needs to be adapted to the new tile generated world.

**Comment by Emir0zcelik** [comment]
issue handled at the commit: [67cba6b](https://github.com/CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers/commit/67cba6b09d01fa8ad0c439c91ed0a0fc6b2221ed)
