### ISSUE TITLE
Building System

### ISSUE THREAD

**Issue by bberkayydemir** [CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers#13]
Make a rotation & preview for all buildings. Also make a wall building system.

**Comment by Emir0zcelik** [comment]
Issue handled at : https://github.com/CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers/commit/25e95a01c11a16a500ed3a8716c9f70d59599c11

**Comment by Emir0zcelik** [comment]
Issue handled at: https://github.com/CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers/commit/25e95a01c11a16a500ed3a8716c9f70d59599c11
