### ISSUE TITLE
More Optimized Grid and Building Manager

### ISSUE THREAD

**Issue by bberkayydemir** [CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers#17]
Grid Manager OutOfIndex bugs must be solved and also Building Manager should be more optimized.

**Comment by Emir0zcelik** [comment]
Issue handled at: [https://github.com/CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers/compare/8eae7aa01ff22c92f5aa9e0eeeaf033c345cb886...965e5567d7e04422e9af00ce68f2618b950c7c3d](url)

**Comment by Emir0zcelik** [comment]
Issue Handled at: 965e5567d7e04422e9af00ce68f2618b950c7c3d
