### ISSUE TITLE
Units Freeze Under Certain Conditions

### ISSUE THREAD

**Issue by Emir0zcelik** [CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers#2]
Units stop functioning when another unit destroys their target and sometimes units are able to attack targets outside their attack range.

**Comment by C-atmaca** [comment]
issue handled at the commit: [76a22edd0924dcf32abfd0971e1ade258ec0c1e2](https://github.com/CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers/commit/76a22edd0924dcf32abfd0971e1ade258ec0c1e2)
