### ISSUE TITLE
Spawn System Improvements

### ISSUE THREAD

**Issue by BAYKO5** [CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers#5]
Spawn system needs to set spawn points on the same horizontal axis as the player base objects so that the units can go straight towards the selected player base. Number of units should be spawned on a logic based on unit power and spawn wave number.

**Comment by C-atmaca** [comment]
Spawn points now align themselves accordingly handled in this commit: https://github.com/CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers/commit/a260af4d3815da3e5622cb181cc1c205102be37f

I am now working on unit spawn logic depending on power and wave number.

**Comment by C-atmaca** [comment]
Issue handled at commit: [dd9956694bd81dc03fe3362f7a1235f6243f72a8](https://github.com/CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers/commit/dd9956694bd81dc03fe3362f7a1235f6243f72a8)
