### ISSUE TITLE
3D Building assets Improvements

### ISSUE THREAD

**Issue by bberkayydemir** [CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers#6]
3D Building assets needs to be flexible by breaking them into smaller, interchangeable parts. All the building moduler parts should align seamlessly with existing structures of the other moduler parts of the building.

**Comment by BAYKO5** [comment]
Issue fixed. 
https://github.com/CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers/commit/2bc1b5c57374456995cac1683d42475fb044bd69
