### ISSUE TITLE
Player Unit AI and Animation Integration

### ISSUE THREAD

**Issue by Emir0zcelik** [CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers#7]
Player units need their AI implemented just like the enemy units. All types of units needs animation integration.

**Comment by C-atmaca** [comment]
Issue handled at commit: https://github.com/CankayaUniversity/ceng-407-408-2023-2024-Night-Keepers/commit/7beb17fee438f33d4fb8ddd87a81d016b159d93a
